load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "types",
    srcs = ["types.go"],
    importpath = "github.com/DICEsda/IOT-TileNodeCoordinator/backend/internal/types",
    visibility = ["//visibility:public"],
)
